const router = require('express').Router();
const PDFDocument = require('pdfkit');
const Complaint = require('../models/Complaint');
const Officer = require('../models/Officer');
const authMiddleware = require('../middleware/authMiddleware');
const adminMiddleware = require('../middleware/adminMiddleware');

router.use(authMiddleware, adminMiddleware);

// GET /api/reports/pdf
router.get('/pdf', async (req, res) => {
  try {
    const { from, to } = req.query;
    const dateFilter = {};
    if (from) dateFilter.$gte = new Date(from);
    if (to) dateFilter.$lte = new Date(to);
    const dateQuery = Object.keys(dateFilter).length ? { createdAt: dateFilter } : {};

    const total = await Complaint.countDocuments(dateQuery);
    const resolved = await Complaint.countDocuments({ ...dateQuery, status: { $in: ['Resolved', 'Closed'] } });
    const overdue = await Complaint.countDocuments({
      ...dateQuery, status: { $nin: ['Resolved', 'Closed'] }, slaDeadline: { $lt: new Date() }
    });
    const escalated = await Complaint.countDocuments({ ...dateQuery, status: 'Escalated' });

    const byDept = await Complaint.aggregate([
      { $match: dateQuery },
      { $group: { _id: '$department', count: { $sum: 1 }, resolved: { $sum: { $cond: [{ $in: ['$status', ['Resolved', 'Closed']] }, 1, 0] } } } },
      { $sort: { count: -1 } }, { $limit: 10 }
    ]);

    const byPriority = await Complaint.aggregate([
      { $match: dateQuery },
      { $group: { _id: '$priority', count: { $sum: 1 } } }
    ]);

    const ratingAgg = await Complaint.aggregate([
      { $match: { ...dateQuery, rating: { $exists: true, $ne: null } } },
      { $group: { _id: null, avgRating: { $avg: '$rating' }, count: { $sum: 1 } } }
    ]);

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=GrievEase-Report-${new Date().toISOString().slice(0,10)}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor('#1e40af').text('GrievEase', { align: 'center' });
    doc.fontSize(10).fillColor('#64748b').text('AI-Powered Public Grievance Platform — Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(9).fillColor('#94a3b8').text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, { align: 'center' });
    doc.moveDown(1.5);

    // Summary
    doc.fontSize(14).fillColor('#1e40af').text('Summary');
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#334155');
    doc.text(`Total Complaints: ${total}`);
    doc.text(`Resolved: ${resolved} (${total ? Math.round((resolved/total)*100) : 0}%)`);
    doc.text(`Overdue: ${overdue}`);
    doc.text(`Escalated: ${escalated}`);
    if (ratingAgg.length > 0) {
      doc.text(`Average Citizen Rating: ${ratingAgg[0].avgRating.toFixed(1)} / 5 (${ratingAgg[0].count} ratings)`);
    }
    doc.moveDown(1);

    // By Department
    doc.fontSize(14).fillColor('#1e40af').text('Complaints by Department');
    doc.moveDown(0.5);
    byDept.forEach(d => {
      const resRate = d.count ? Math.round((d.resolved / d.count) * 100) : 0;
      doc.fontSize(9).fillColor('#334155').text(`  ${d._id || 'Unassigned'}: ${d.count} total, ${d.resolved} resolved (${resRate}%)`);
    });
    doc.moveDown(1);

    // By Priority
    doc.fontSize(14).fillColor('#1e40af').text('Complaints by Priority');
    doc.moveDown(0.5);
    byPriority.forEach(p => {
      doc.fontSize(9).fillColor('#334155').text(`  ${p._id}: ${p.count}`);
    });
    doc.moveDown(2);

    doc.fontSize(8).fillColor('#94a3b8').text('Auto-generated by GrievEase AI Platform', { align: 'center' });
    doc.end();
  } catch (err) {
    console.error('PDF error:', err);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

module.exports = router;
